// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqvthwcaxloneospaahd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxdnRod2NheGxvbmVvc3BhYWhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMDI1ODMsImV4cCI6MjA2OTc3ODU4M30.FzBA2gR4qfFVKpm_tf-m9qORO8PfI3vXN7c7A1SF5oE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});